apiVersion: apps/v1
kind: Deployment
metadata: 
  name: cteseproject2
spec: 
  selector:
    matchLabels:
      app: cteseproject2
  replicas: 2
  template:
    metadata:
      labels:
        app: cteseproject2
    spec:
      containers:
        - name: cteseproject2
          image: it19132624/cteseproject2
          ports:
            - containerPort: 5000